apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clock
  template:
    metadata:
      labels:
        name: clock
    spec:
      serviceAccountName: clock
      containers:
        - name: clock
          # Replace this with the built image name
          image: gcr.io/gabrielhome/crd/clock:latest
          command:
          - clock
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "clock"
