kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clock
subjects:
- kind: ServiceAccount
  name: clock
roleRef:
  kind: Role
  name: clock
  apiGroup: rbac.authorization.k8s.io
