apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clocks.clock.iamthat.com
spec:
  group: clock.iamthat.com
  names:
    kind: Clock
    listKind: ClockList
    plural: clocks
    singular: clock
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Clock is the Schema for the clocks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClockSpec defines the desired state of Clock
          properties:
            current_day:
              type: string
            current_time:
              type: string
            reset:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
          required:
          - current_day
          - current_time
          - reset
          type: object
        status:
          description: ClockStatus defines the observed state of Clock
          properties:
            current_day:
              type: string
            current_time:
              type: string
            reset:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
          required:
          - current_day
          - current_time
          - reset
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
